AWSTemplateFormatVersion: "2010-09-09"
Description: ALB for USER API

Parameters:
  ProjectName:
    Type: String
    Default: user-api
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  DomainName:
    Type: String

Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${ProjectName}-TargetGroupArn
  AlbDnsName:
    Value: !GetAtt ALB.DNSName

Resources:
  # Application Load Blancer
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-alb
      Scheme: internet-facing
      Type: application
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-alb
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation
      Subnets:
        - !ImportValue
          Fn::Sub: ${ProjectName}-PublicSubnet1Id
        - !ImportValue
          Fn::Sub: ${ProjectName}-PublicSubnet2Id
      SecurityGroups:
        - !ImportValue
          Fn::Sub: ${ProjectName}-AlbSecurityGroupId

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-tg
      VpcId: !ImportValue
        Fn::Sub: ${ProjectName}-VpcId
      Protocol: HTTP
      Port: 3000
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-tg
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # Listener (HTTPS)
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # Dns Record
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ALB.DNSName
        HostedZoneId: !GetAtt ALB.CanonicalHostedZoneID
