AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for User API

Parameters:
  ProjectName:
    Type: String
    Default: user-api

Outputs:
  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
    Export:
      Name: !Sub ${ProjectName}-RepositoryUri

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [{
              "rulePriority": 1,
              "description": "keep only 3 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 3
              },
              "action": {"type": "expire"}
            }]
          }